//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yogiram.core.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class AT_Modules
    {
        public System.Guid ModuleId { get; set; }
        public string ModuleName { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
