//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yogiram.core.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMaster
    {
        public CompanyMaster()
        {
            this.ComponentMaster = new HashSet<ComponentMaster>();
            this.EmployeeMaster = new HashSet<EmployeeMaster>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string TelphoneNo { get; set; }
        public string OfficialMail { get; set; }
        public string Country { get; set; }
        public string CompanyShortName { get; set; }
        public int Pincode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<ComponentMaster> ComponentMaster { get; set; }
        public virtual ICollection<EmployeeMaster> EmployeeMaster { get; set; }
    }
}
