//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yogiram.core.DataSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoreEntities : DbContext
    {
        public CoreEntities()
            : base("name=CoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AT_Roles> AT_Roles { get; set; }
        public DbSet<TblRegister> TblRegister { get; set; }
        public DbSet<AT_Menu> AT_Menu { get; set; }
        public DbSet<AT_RolesForMenu> AT_RolesForMenu { get; set; }
        public DbSet<CompanyMaster> CompanyMaster { get; set; }
        public DbSet<ComponentMaster> ComponentMaster { get; set; }
        public DbSet<AT_User> AT_User { get; set; }
        public DbSet<AT_UserInRoles> AT_UserInRoles { get; set; }
        public DbSet<EmployeeMaster> EmployeeMaster { get; set; }
        public DbSet<AT_Modules> AT_Modules { get; set; }
        public DbSet<DeviceLogs> DeviceLogs { get; set; }
    }
}
