//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yogiram.core.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int EmployeeId { get; set; }
        public int CompanyId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string MartialStatus { get; set; }
        public string PerAddress { get; set; }
        public string PerCity { get; set; }
        public Nullable<int> PerPincode { get; set; }
        public decimal MobileNo { get; set; }
        public string TempAddress { get; set; }
        public string TempCity { get; set; }
        public Nullable<int> TempPincode { get; set; }
        public string Email { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Password { get; set; }
        public string Pass_Salt { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> DateofJoin { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<System.DateTime> EmpTermDate { get; set; }
        public Nullable<int> DesiginationId { get; set; }
        public string Photo { get; set; }
        public string BloodGroup { get; set; }
        public string EmpDescription { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> PassExpDate { get; set; }
        public string PassModified { get; set; }
        public Nullable<System.DateTime> PassUpdateOn { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
    }
}
